Repository googleapis/java-dialogflow-cx, pull requests merged in 2020-12, with the labels that each got.

#100 samples: add sample code to query regional Dialogflow CX agent
  samples/snippets/src/main/java/dialogflow/cx/CreateFlow.java
  samples/snippets/src/main/java/dialogflow/cx/CreateIntent.java
  samples/snippets/src/main/java/dialogflow/cx/CreatePage.java
  samples/snippets/src/main/java/dialogflow/cx/DetectIntent.java
  samples/snippets/src/main/java/dialogflow/cx/DetectIntentStream.java
  samples/snippets/src/test/java/dialogflow/cx/CreateFlowIT.java
  samples/snippets/src/test/java/dialogflow/cx/CreateIntentIT.java
  samples/snippets/src/test/java/dialogflow/cx/CreatePageIT.java
  samples/snippets/src/test/java/dialogflow/cx/DetectIntentIT.java
  samples/snippets/src/test/java/dialogflow/cx/DetectIntentStreamIT.java
Labels: api: dialogflow, cla: yes, samples

#103 fix: change location in IT to be 'global'
  google-cloud-dialogflow-cx/src/test/java/com/google/cloud/dialogflow/cx/v3beta1/it/ITSystemTest.java
Labels: api: dialogflow, cla: yes

#104 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#118 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#116 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/blunderbuss.yml
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  .kokoro/common.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full

#120 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/generated-files-bot.yml
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full
