Repository googleapis/java-dialogflow-cx, pull requests merged in 2020-09, with the labels that each got.

#15 samples: add sample codes for Dialogflow CX.
  samples/install-without-bom/resources/book_a_room.wav
  samples/snapshot/resources/book_a_room.wav
  samples/snippets/resources/book_a_room.wav
  samples/snippets/src/main/java/dialogflow/cx/CreateFlow.java
  samples/snippets/src/main/java/dialogflow/cx/CreateIntent.java
  samples/snippets/src/main/java/dialogflow/cx/CreatePage.java
  samples/snippets/src/main/java/dialogflow/cx/DetectIntent.java
  samples/snippets/src/main/java/dialogflow/cx/DetectIntentStream.java
  samples/snippets/src/test/java/dialogflow/cx/CreateFlowIT.java
  samples/snippets/src/test/java/dialogflow/cx/CreateIntentIT.java
  samples/snippets/src/test/java/dialogflow/cx/CreatePageIT.java
  samples/snippets/src/test/java/dialogflow/cx/DetectIntentIT.java
  samples/snippets/src/test/java/dialogflow/cx/DetectIntentStreamIT.java
Labels: api: dialogflow, cla: yes

#20 chore: regenerate README
  README.md
  synth.metadata
Labels: api: dialogflow, cla: yes, context: none

#22 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#32 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: dialogflow, automerge, cla: yes

#38 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#39 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
