Repository googleapis/java-dialogflow-cx, pull requests merged in 2020-08, with the labels that each got.

#7 chore: add samples lint presubmit
  .github/workflows/samples.yaml
  synth.metadata
Labels: cla: yes, context: full

#11 chore: fix samples dependencies so tests pass
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes

#14 build: switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  README.md
  synth.metadata
Labels: cla: yes, context: partial
