Repository googleapis/java-dialogflow-cx, pull requests merged in 2020-11, with the labels that each got.

#67 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#69 fix!: remove empty proto classes GcsProto and InteractiveVoiceResponseProto
  proto-google-cloud-dialogflow-cx-v3beta1/clirr-ignored-differences.xml
  proto-google-cloud-dialogflow-cx-v3beta1/src/main/java/com/google/cloud/dialogflow/cx/v3beta1/GcsProto.java
  proto-google-cloud-dialogflow-cx-v3beta1/src/main/java/com/google/cloud/dialogflow/cx/v3beta1/InteractiveVoiceResponseProto.java
  proto-google-cloud-dialogflow-cx-v3beta1/src/main/proto/google/cloud/dialogflow/cx/v3beta1/gcs.proto
  proto-google-cloud-dialogflow-cx-v3beta1/src/main/proto/google/cloud/dialogflow/cx/v3beta1/ivr.proto
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#68 test(dialogflow-cx): add integration test for v3beta1
  google-cloud-dialogflow-cx/pom.xml
  google-cloud-dialogflow-cx/src/test/java/com/google/cloud/dialogflow/cx/v3beta1/it/ITSystemTest.java
Labels: api: dialogflow, cla: yes

#73 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#75 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#82 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#84 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#83 feat: expose matched event in Sessions API.
  proto-google-cloud-dialogflow-cx-v3beta1/src/main/java/com/google/cloud/dialogflow/cx/v3beta1/Match.java
  proto-google-cloud-dialogflow-cx-v3beta1/src/main/java/com/google/cloud/dialogflow/cx/v3beta1/MatchOrBuilder.java
  proto-google-cloud-dialogflow-cx-v3beta1/src/main/java/com/google/cloud/dialogflow/cx/v3beta1/SessionProto.java
  proto-google-cloud-dialogflow-cx-v3beta1/src/main/proto/google/cloud/dialogflow/cx/v3beta1/session.proto
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#88 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes
